name: CI Validation

on:
  push:
    branches:
      - test/validation-run
  pull_request:
    branches:
      - test/validation-run

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack & Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install --frozen-lockfile

      - name: Type check
        run: npx tsc --noEmit

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build
